version: '3.8'

services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./build:/app/build
    environment:
      - NODE_ENV=production
    command: ["npm", "run", "build"]

  nginx:
    image: nginx:latest
    depends_on:
      - frontend
    ports:
      - "80:8080"  # Porta externa 80 mapeia para porta interna 8080 do Nginx
    volumes:
      - ./docker/nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./default.conf:/etc/nginx/conf.d/default.conf:ro
      - ./build:/usr/share/nginx/html:ro
