version: '3.9'

services:
  react-app:
    build: .
    environment:
      SIP_CLIENT_ID:  "${REACT_APP_SIP_CLIENT_ID}"
      SIP_SECRET:  "${REACT_APP_SIP_SECRET}"
    ports:
      - "80:80"
    restart: always
