name: Deploy React App to EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout do repositório
        uses: actions/checkout@v3

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Instalar dependências e build
        run: |
          npm install
          CI='' npm run build

      - name: Copiar arquivos para a EC2
        uses: appleboy/scp-action@v0.1.4
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.AWS_REACT_EC2_SSH_KEY }}
          source: "."
          target: "~/react-app"

      - name: Deploy via SSH na EC2
        uses: appleboy/ssh-action@v0.1.8
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.AWS_REACT_EC2_SSH_KEY }}
          script: |
            # Verificar se o Docker está instalado
            if ! command -v docker &> /dev/null
            then
                echo "🔧 Docker não encontrado. Instalando..."
                sudo apt-get update
                sudo apt-get install -y docker.io docker-compose
                sudo systemctl start docker
                sudo systemctl enable docker
                sudo usermod -aG docker $USER
                newgrp docker
            fi

            # Continuar com os comandos Docker após instalação
            cd ~/react-app
            docker compose down --rmi all --volumes --remove-orphans
            docker compose build --no-cache
            docker compose up -d
