name: Deploy Docker App to EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout código
        uses: actions/checkout@v3

      - name: Copiar arquivos via SSH
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.AWS_REACT_EC2_SSH_KEY }}
          source: "."
          target: "~/react-app"

      - name: Executar Docker no EC2
        uses: appleboy/ssh-action@v0.1.8
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.AWS_REACT_EC2_SSH_KEY }}
          script: |
            cd ~/react-app

            # Parar e remover container antigo, se existir
            docker kill react-app || true
            docker rm -f react-app || true

            # Liberar a porta 80 caso esteja travada
            sudo fuser -k 80/tcp || true

            # Construir nova imagem Docker
            docker build -t react-app .

            # Subir o novo container
            docker run -d --name react-app -p 80:80 react-app
