name: Deploy React App to EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout do repositório
        uses: actions/checkout@v3

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Instalar dependências e build
        run: |
          npm install
          CI='' npm run build

      - name: Copiar arquivos para a EC2
        uses: appleboy/scp-action@v0.1.4
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.AWS_REACT_EC2_SSH_KEY }}
          source: "."
          target: "~/react-app"

      - name: Deploy via SSH na EC2
        uses: appleboy/ssh-action@v0.1.8
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.AWS_REACT_EC2_SSH_KEY }}
          command_timeout: 1200
          script: |
            # Navegar para o diretório da aplicação
            cd ~/react-app

            # Parar e remover containers, volumes e orphans
            docker-compose down --volumes --remove-orphans

            # Construir novamente as imagens sem cache
            docker-compose up --build -d
